resource_types:
# notify: &notify
#   put: slack-message
#   params:
#     channel:
#       - 'ms-ops'
#       - '#terraform-prs'
#     text: |
#       :tada: Something in the build has failed. Check it out at:
#       http://management-concourse.prod.transit.ri-tech.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

resources:
- name: git-alpine_toolbox
  type: git
  source:
    uri: https://github.com/stefancocora/alpine-toolbox.git
    branch: master
    disable_ci_skip: true
- name: img-quay-alpine-toolbox
  type: docker-image
  source:
    repository: quay.io/stefancocora/alpine-toolbox
    username: ((alpine_toolbox_user))
    password: ((alpine_toolbox_pass))


jobs:
- name: build-img
  public: true
  plan:
  - get: git-alpine_toolbox
    trigger: true
    version: every
  - aggregate:
    - put: img-quay-alpine-toolbox
      params:
        build: git-alpine_toolbox
    # on_failure: *notify
# this is how starkandwayne publish docker images
# https://github.com/starkandwayne/dockerfiles/blob/master/concourse-go/1.11/pipeline.yml
# should fetch the "rc" image and retag it to latest/v0.0.x
# and that should be the publish step
- name: publish-img
  public: true
  plan:
  - get: git-alpine_toolbox
    trigger: true
    version: every
    passed: [build-img]
  - aggregate:
    - put: img-quay-alpine-toolbox
      params:
        build: git-alpine_toolbox
        tag_prefix: v
        tag_file: git-alpine_toolbox/VERSION
        tag_as_latest: true
    # on_failure: *notify
