resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: git-alpine_toolbox
  type: pull-request
  check_every: 1m
  source:
    repository: stefancocora/alpine-toolbox
    access_token: ((github-access-token))
- name: img-quay-alpine-toolbox
  type: docker-image
  source:
    repository: quay.io/stefancocora/alpine-toolbox
    tag_file: VERSION
    tag_as_latest: true
    username: ((alpine_toolbox_user))
    password: ((alpine_toolbox_pass))


jobs:
- name: build-img
  public: true
  plan:
  - get: git-alpine_toolbox
    trigger: true
    version: every
  - aggregate:
    - put: img-quay-alpine-toolbox
      params:
        build: git-alpine_toolbox
    on_failure:
      put: git-alpine_toolbox
      params:
        path: git-alpine_toolbox
        status: failure
        context: "build-img"
    on_success:
      put: git-alpine_toolbox
      params:
        path: git-alpine_toolbox
        status: success
        context: "build-img"
- name: publish-img
  public: true
  plan:
  - get: git-alpine_toolbox
    trigger: true
    version: every
    passed: [build-img]
  - aggregate:
    - put: img-quay-alpine-toolbox
      params:
        build: git-alpine_toolbox
    on_failure:
      put: git-alpine_toolbox
      params:
        path: git-alpine_toolbox
        status: failure
        context: "publish-img"
    on_success:
      put: git-alpine_toolbox
      params:
        path: git-alpine_toolbox
        status: success
        context: "publish-img"
